# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1071, 817)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 336, 773))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_4.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_4.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.param_learning_steps_txt = QtWidgets.QLineEdit(self.groupBox_2)
        self.param_learning_steps_txt.setObjectName("param_learning_steps_txt")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.param_learning_steps_txt)
        self.epsilon_min_label = QtWidgets.QLabel(self.groupBox_2)
        self.epsilon_min_label.setObjectName("epsilon_min_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.epsilon_min_label)
        self.epsilon_min_txt = QtWidgets.QLineEdit(self.groupBox_2)
        self.epsilon_min_txt.setObjectName("epsilon_min_txt")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.epsilon_min_txt)
        self.epsilon_max_label = QtWidgets.QLabel(self.groupBox_2)
        self.epsilon_max_label.setObjectName("epsilon_max_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.epsilon_max_label)
        self.epsilon_max_txt = QtWidgets.QLineEdit(self.groupBox_2)
        self.epsilon_max_txt.setObjectName("epsilon_max_txt")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.epsilon_max_txt)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.param_improve_every_steps_txt = QtWidgets.QLineEdit(self.groupBox_2)
        self.param_improve_every_steps_txt.setObjectName("param_improve_every_steps_txt")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.param_improve_every_steps_txt)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.cbInvertLearning = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbInvertLearning.setText("")
        self.cbInvertLearning.setObjectName("cbInvertLearning")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cbInvertLearning)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.choose_learning_algorithm = QtWidgets.QComboBox(self.groupBox_2)
        self.choose_learning_algorithm.setObjectName("choose_learning_algorithm")
        self.choose_learning_algorithm.addItem("")
        self.choose_learning_algorithm.addItem("")
        self.choose_learning_algorithm.addItem("")
        self.choose_learning_algorithm.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.choose_learning_algorithm)
        self.horizontalLayout.addLayout(self.formLayout)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.one_arm_rb = QtWidgets.QRadioButton(self.groupBox_4)


        self.one_arm_rb.setObjectName("one_arm_rb")
        self.verticalLayout_7.addWidget(self.one_arm_rb)
        self.two_arm_all_action_rb = QtWidgets.QRadioButton(self.groupBox_4)
        self.two_arm_all_action_rb.setObjectName("two_arm_all_action_rb")
        self.verticalLayout_7.addWidget(self.two_arm_all_action_rb)

        self.two_arm_all_action_rb.setEnabled(True)
        self.two_arm_all_action_rb.setChecked(True)

        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.param_min_deg_j1_txt = QtWidgets.QLineEdit(self.groupBox_4)
        self.param_min_deg_j1_txt.setObjectName("param_min_deg_j1_txt")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.param_min_deg_j1_txt)
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.param_max_deg_j1_txt = QtWidgets.QLineEdit(self.groupBox_4)
        self.param_max_deg_j1_txt.setObjectName("param_max_deg_j1_txt")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.param_max_deg_j1_txt)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.param_min_deg_j2_txt = QtWidgets.QLineEdit(self.groupBox_4)
        self.param_min_deg_j2_txt.setObjectName("param_min_deg_j2_txt")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.param_min_deg_j2_txt)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.param_max_deg_j2_txt = QtWidgets.QLineEdit(self.groupBox_4)
        self.param_max_deg_j2_txt.setObjectName("param_max_deg_j2_txt")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.param_max_deg_j2_txt)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.param_deg_steps_j1_txt = QtWidgets.QLineEdit(self.groupBox_4)
        self.param_deg_steps_j1_txt.setObjectName("param_deg_steps_j1_txt")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.param_deg_steps_j1_txt)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.param_deg_steps_j2_txt = QtWidgets.QLineEdit(self.groupBox_4)
        self.param_deg_steps_j2_txt.setObjectName("param_deg_steps_j2_txt")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.param_deg_steps_j2_txt)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.servo_speed_slider = QtWidgets.QSlider(self.groupBox_4)
        self.servo_speed_slider.setMinimum(10)
        self.servo_speed_slider.setMaximum(40)
        self.servo_speed_slider.setSingleStep(1)
        self.servo_speed_slider.setSliderPosition(10)
        self.servo_speed_slider.setTracking(True)
        self.servo_speed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.servo_speed_slider.setObjectName("servo_speed_slider")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.servo_speed_slider)
        self.verticalLayout_7.addLayout(self.formLayout_2)
        self.verticalLayout_9.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.speed_slider = QtWidgets.QSlider(self.groupBox_5)
        self.speed_slider.setMaximum(100)
        self.speed_slider.setSingleStep(1)
        self.speed_slider.setSliderPosition(0)
        self.speed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.speed_slider.setObjectName("speed_slider")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.speed_slider)
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.cbDrawRobot = QtWidgets.QCheckBox(self.groupBox_5)
        self.cbDrawRobot.setText("")
        self.cbDrawRobot.setChecked(False)
        self.cbDrawRobot.setObjectName("cbDrawRobot")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cbDrawRobot)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setEnabled(True)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.cbDrawSumValueTable = QtWidgets.QCheckBox(self.groupBox_5)
        self.cbDrawSumValueTable.setText("")
        self.cbDrawSumValueTable.setChecked(True)
        self.cbDrawSumValueTable.setObjectName("cbDrawSumValueTable")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cbDrawSumValueTable)
        self.verticalLayout_4.addLayout(self.formLayout_3)
        self.verticalLayout_9.addWidget(self.groupBox_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_8.addWidget(self.scrollArea)
        self.verticalLayout_2.addLayout(self.verticalLayout_8)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.groupBox_3)
        self.frame.setObjectName("frame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.start_learning_button = QtWidgets.QPushButton(self.frame)
        self.start_learning_button.setAutoDefault(False)
        self.start_learning_button.setObjectName("start_learning_button")
        self.verticalLayout_14.addWidget(self.start_learning_button)
        self.pause_learning_button = QtWidgets.QPushButton(self.frame)
        self.pause_learning_button.setObjectName("pause_learning_button")
        self.verticalLayout_14.addWidget(self.pause_learning_button)
        self.widget1 = QtWidgets.QWidget(self.frame)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.execute_button = QtWidgets.QPushButton(self.widget1)
        self.execute_button.setObjectName("execute_button")
        self.horizontalLayout_6.addWidget(self.execute_button)
        self.save_policy_button = QtWidgets.QPushButton(self.widget1)
        self.save_policy_button.setObjectName("save_policy_button")
        self.horizontalLayout_6.addWidget(self.save_policy_button)
        self.load_policy_button = QtWidgets.QPushButton(self.widget1)
        self.load_policy_button.setObjectName("load_policy_button")
        self.horizontalLayout_6.addWidget(self.load_policy_button)
        self.verticalLayout_14.addWidget(self.widget1)
        self.stop_robot_button = QtWidgets.QPushButton(self.frame)
        self.stop_robot_button.setAutoDefault(False)
        self.stop_robot_button.setDefault(False)
        self.stop_robot_button.setFlat(False)
        self.stop_robot_button.setObjectName("stop_robot_button")
        self.verticalLayout_14.addWidget(self.stop_robot_button)
        self.verticalLayout_3.addWidget(self.frame)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.horizontalLayout_4.addWidget(self.widget)
        self.scroll_area = QtWidgets.QScrollArea(self.centralwidget)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 695, 793))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.simu_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.simu_widget.setObjectName("simu_widget")
        self.verticalLayout_simu = QtWidgets.QVBoxLayout(self.simu_widget)
        self.verticalLayout_simu.setObjectName("verticalLayout_simu")
        self.label_10 = QtWidgets.QLabel(self.simu_widget)
        self.label_10.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_simu.addWidget(self.label_10)
        self.verticalLayout.addWidget(self.simu_widget)
        self.monitoring_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.monitoring_widget.setObjectName("monitoring_widget")
        self.verticalLayout_monitoring = QtWidgets.QVBoxLayout(self.monitoring_widget)
        self.verticalLayout_monitoring.setObjectName("verticalLayout_monitoring")
        self.label_steps = QtWidgets.QLabel(self.monitoring_widget)
        self.label_steps.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_steps.setObjectName("label_steps")
        self.verticalLayout_monitoring.addWidget(self.label_steps)
        self.label_11 = QtWidgets.QLabel(self.monitoring_widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_11.setFont(font)
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_monitoring.addWidget(self.label_11)
        self.value_graph_widget = QtWidgets.QWidget(self.monitoring_widget)
        self.value_graph_widget.setObjectName("value_graph_widget")
        self.verticalLayout_monitoring.addWidget(self.value_graph_widget)
        self.verticalLayout.addWidget(self.monitoring_widget)
        self.scroll_area.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_4.addWidget(self.scroll_area)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Learning"))
        self.label_2.setText(_translate("MainWindow", "Learning steps"))
        self.epsilon_min_label.setText(_translate("MainWindow", "Min. epsilon (>=0.1)"))
        self.epsilon_max_label.setText(_translate("MainWindow", "Max. epsilon (<=1.0)"))
        self.label_14.setText(_translate("MainWindow", "Improve every x steps"))
        self.label_12.setText(_translate("MainWindow", "Learn backward crawling"))
        self.label_18.setText(_translate("MainWindow", "Learning Algorithm"))
        self.choose_learning_algorithm.setCurrentText(_translate("MainWindow", "Value Iteration"))
        self.choose_learning_algorithm.setItemText(0, _translate("MainWindow", "Value Iteration"))
        self.choose_learning_algorithm.setItemText(1, _translate("MainWindow", "Q Learning"))
        self.choose_learning_algorithm.setItemText(2, _translate("MainWindow", "DQN Learning"))
        self.choose_learning_algorithm.setItemText(3, _translate("MainWindow", "Walk Around"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Robot"))
        self.one_arm_rb.setText(_translate("MainWindow", "One Arm"))
        self.two_arm_all_action_rb.setText(_translate("MainWindow", "Two Arms - All action possible"))
        self.label.setText(_translate("MainWindow", "Min. degree for joint 1"))
        self.label_3.setText(_translate("MainWindow", "Max. degree for joint 1"))
        self.label_4.setText(_translate("MainWindow", "Min. degree for joint 2"))
        self.label_5.setText(_translate("MainWindow", "Max. degree for joint 2"))
        self.label_6.setText(_translate("MainWindow", "Degree steps for joint 1"))
        self.label_7.setText(_translate("MainWindow", "Degree steps for joint 2"))
        self.label_8.setText(_translate("MainWindow", "Servo speed"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Simulation"))
        self.label_16.setText(_translate("MainWindow", "Speed"))
        self.label_15.setText(_translate("MainWindow", "Draw robot"))
        self.label_13.setText(_translate("MainWindow", "Draw sum of value table"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Control"))
        self.start_learning_button.setToolTip(_translate("MainWindow", "Starts the reinforcment learning."))
        self.start_learning_button.setText(_translate("MainWindow", "Start learning"))
        self.pause_learning_button.setToolTip(_translate("MainWindow", "Option to stop and restart the learning algorithm."))
        self.pause_learning_button.setText(_translate("MainWindow", "Pause learning"))
        self.execute_button.setText(_translate("MainWindow", "Execute Policy"))
        self.save_policy_button.setText(_translate("MainWindow", "Save Policy"))
        self.load_policy_button.setText(_translate("MainWindow", "Load Policy"))
        self.stop_robot_button.setToolTip(_translate("MainWindow", "Stops the reinforcement learning and rests to default."))
        self.stop_robot_button.setText(_translate("MainWindow", "Stop robot"))
        self.label_10.setText(_translate("MainWindow", "Simulation"))
        self.label_steps.setText(_translate("MainWindow", "Steps:"))
        self.label_11.setText(_translate("MainWindow", "Monitoring"))
